// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJzBa7AgaZTIXKJqAn1ucQw2IqsUg4Ak',
    appId: '1:1040531108841:web:38b8e2fc24e0b326e35178',
    messagingSenderId: '1040531108841',
    projectId: 'on-time-ea93b',
    authDomain: 'on-time-ea93b.firebaseapp.com',
    storageBucket: 'on-time-ea93b.firebasestorage.app',
    measurementId: 'G-CETZ65N8W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ReMFQiX1RxVs0mabhQ19Dp-TMbbYCPc',
    appId: '1:1040531108841:android:5b2fcee21efb611ae35178',
    messagingSenderId: '1040531108841',
    projectId: 'on-time-ea93b',
    storageBucket: 'on-time-ea93b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpWKUSv6JAR6FeV7QdUQ3iU5tLBmFAkU',
    appId: '1:1040531108841:ios:aa49c9517161b06ae35178',
    messagingSenderId: '1040531108841',
    projectId: 'on-time-ea93b',
    storageBucket: 'on-time-ea93b.firebasestorage.app',
    iosBundleId: 'com.ontimeapp.onTimeApp',
  );
}
